# Generated by Django 5.2.5 on 2025-08-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.TextField(max_length=100, verbose_name='Marca')),
                ('nombre', models.TextField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('disponibilidad', models.BooleanField(default=True, verbose_name='Disponibilidad')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='logos', verbose_name='Imagen')),
            ],
        ),
    ]
